update release dates on milestones. starting release scripts.
revel/meta pull request #6
Opened 2017-05-06 23:07 UTC by shawncatz

2017-05-07 17:59 UTC, notzippy requested changes

2017-05-07 17:59 UTC, notzippy commented on release/prepare.sh
> +        git merge master
On merge failure what happens ?

2017-05-07 17:59 UTC, notzippy commented on release/changelog.sh
> +    lines=$(git --no-pager -C ${src}/${r} log --oneline master..develop)
Rather then using the commit log, we should be looking to fetch the PR data, and issues from github https://github.com/skywinder/github-changelog-generator

2017-05-07 18:04 UTC, shawncatz commented on release/changelog.sh
> +    lines=$(git --no-pager -C ${src}/${r} log --oneline master..develop)
yeah, this was just a first pass, I planned on integration with the generator, just needed to get things working first.

2017-05-07 18:04 UTC, shawncatz commented on release/prepare.sh
> +        git merge master
BOOM!

2017-05-07 18:05 UTC, shawncatz commented on release/changelog.sh
> +    lines=$(git --no-pager -C ${src}/${r} log --oneline master..develop)
I will work on that once I've got the other stuff nailed down... testing the release process right now

2017-05-09 04:34 UTC, shawncatz commented
@brendensoares @notzippy are we going to try to do the release tomorrow night? I think this is ready to try.
Or we can try Thursday... whichever works for you both

2017-05-19 05:08 UTC, brendensoares commented
Well we did a release with these scripts and it went well overall. I'd say merge it. We can expand on the work you did for Go-based tools as well.

Thanks @shawncatz

2017-05-19 05:14 UTC, brendensoares approved these changes

2017-05-29 23:14 UTC, merged